# "The Matrix is a system, Neo."
# Matrix-style Powerlevel10k config — black bg, green text
'builtin' 'local' -a __p9k_src_params
__p9k_src_params=("${@}")

typeset -g POWERLEVEL9K_MODE=nerdfont-v3
typeset -g POWERLEVEL9K_ICON_PADDING=moderate

# Prompt style — lean (no background segments, clean look)
typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=false
typeset -g POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

# Matrix green: 034 = bright green
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs prompt_char)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs node_version virtualenv pyenv time)

# Directory styling
typeset -g POWERLEVEL9K_DIR_FOREGROUND=034
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=028
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=040
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=3

# VCS (git) styling
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=040
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=178
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=034

# Status
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=040
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=196

# Command execution time
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=028

# Time
typeset -g POWERLEVEL9K_TIME_FOREGROUND=034
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'

# Background jobs
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=040

# Separators — lean style, no powerline arrows
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '

# No background colors (let terminal black show through)
typeset -g POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=' '
typeset -g POWERLEVEL9K_DIR_BACKGROUND=clear
typeset -g POWERLEVEL9K_VCS_BACKGROUND=clear
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=clear
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=clear
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=clear
typeset -g POWERLEVEL9K_TIME_BACKGROUND=clear
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=clear

# "You have to let it all go."
# Prompt character — green ">" for that classic terminal hacker look
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=040
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=196
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_CONTENT_EXPANSION='>'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_CONTENT_EXPANSION='>'
typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=clear

# Node version — Matrix green
typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=034
typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND=clear
typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true

# Python virtualenv / pyenv — Matrix green
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=040
typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=clear
typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true
typeset -g POWERLEVEL9K_PYENV_FOREGROUND=040
typeset -g POWERLEVEL9K_PYENV_BACKGROUND=clear

# Matrix-y nerdfont icons
typeset -g POWERLEVEL9K_DIR_FOLDER_ICON='\uF115'
typeset -g POWERLEVEL9K_VCS_GIT_ICON='\uF1D3'
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uE0A0 '
typeset -g POWERLEVEL9K_TIME_ICON='\uF017'
typeset -g POWERLEVEL9K_NODE_VERSION_VISUAL_IDENTIFIER_EXPANSION='\u2B22'
typeset -g POWERLEVEL9K_PYTHON_ICON='\uE606'
typeset -g POWERLEVEL9K_EXECUTION_TIME_ICON='\uF252'
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_ICON='\uF013'

# Transient prompt — minimal green ">"
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=same-dir
typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

# "There is no spoon."
